### PR TITLE
Add support for nautical units (#61)

### PR DESCRIPTION
**Pull request by mbof**
Tested manually with nautical GPS tracks, this seems to work.

image

* I pushed some conversions from `WithUnits.svelte` down to `utils.ts` — just as much as I needed to avoid repeating them, but perhaps more even can be pushed into utils.
* To keep the panel reactive, I added parameters to the utility functions so that the framework could keep track of changes and update the values. I gave them default values so as not to break any other unknown cases.

This code is not formatted. If you feel like it's on the right track, pls let me know and I'll format it (if you have a preferred formatter, pls lmk).

### CODE REVIEW

**Comment by mbof** [comment]
I notice at least a couple more places that likely need updating:
* The embedding component `website/src/lib/components/embedding/Embedding.ts` / `website/src/lib/components/embedding/EmbeddingPlayground.svelte`
* The time update form `website/src/lib/components/toolbar/tools/Time.svelte` image

**Comment by vcoppe** [comment]
Nice, I think you have found everything that must be adapted 👍
I have done a first check and it seems to be working fine. I only renamed the `current...Units` parameters to `target...Units`, and added the one for elevation that was missing.

My only comment is about the elevation units: you haven't changed the logic yet, so currently `ft` is used when using the nautical units. I guess that does not make sense, but is one preferred over the other?
Or is one or the other used depending on the country? This would be a bit annoying because then there would not be a simple mapping from distance units to elevation units, and an additional input could be required.

**Comment by mbof** [comment]
Thanks for the review and change! 

Elevation is an interesting question. In my limited experience on the water, it comes up​ in country-dependent units when talking about the depth of water​ (meters, feet or fathoms), or the height of onshore landmarks such as towers and lighthouses​ (meters or feet), but never the elevation of the track itself.​

Thus I'm not sure it really matters in practice and would suggest waiting for more user input before taking on the complication of an extra setting or extra values for the distanceUnits type, so that we can learn more about the context in which it would be useful.

Right now, elevation is in feet in the nautical mode, and if you prefer it to default to meters when in the nautical mode, I'm happy to change it to that though.

What are your thoughts?

(Also, I plan to run prettier on these changes if that's your choice of formatter — I see a .prettierrc so I assume it might be.)

**Comment by vcoppe** [comment]
Thanks for your input.
The website is currently much more popular in Europe than in other regions, so if I had to choose a default elevation unit for the nautical mode, it would be in meters. If you have some time to change this, I think your PR would be ready to be merged :)

**Comment by mbof** [comment]
Makes sense — I manually tested with my last commit and it seems to switch elevation to meters alright. Thanks!

**Pull request merged**
